- name: Set up Python 3.8
  if: github.event_name == 'pull_request'
  uses: actions/setup-python@v4.5.0
  with:
    python-version: 3.8
        
- name: Scan with Checkov
  id: checkov
  uses: bridgecrewio/checkov-action@v12.1347.0
  with:
    directory: ${{ matrix.dir }}
    framework: terraform 
    output_format: cli
    download_external_modules: true
