- name: Post Terraform Plan to PR
  uses: actions/github-script@v6
  env:
    PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
  with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        // Try to find the starting index of the desired sections.
        const planOutput = process.env.PLAN.indexOf('Terraform used the selected providers to generate the following execution');
        const noChanges = process.env.PLAN.indexOf('No changes. Your infrastructure matches the configuration.');

        let filteredPlan = "";

        // Check which section is present and capture the appropriate content.
        if (planOutput !== -1) {
          filteredPlan = process.env.PLAN.slice(planOutput);
        } else if (noChanges !== -1) {
          filteredPlan = 'No changes. Your infrastructure matches the configuration.';
        } else {
          filteredPlan = process.env.PLAN; // fallback to the original content if neither section is found.
        }
            
        // 1. Retrieve existing bot comments for the PR
        const { data: comments } = await github.rest.issues.listComments({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: context.issue.number,
        })
        const botComment = comments.find(comment => {
          return comment.user.type === 'Bot' && comment.body.includes('Checkov Scan Results-${{ matrix.dir }}')
        })

        // 2. Prepare format of the comment
        const output = `#### Checkov Scan Results-${{ matrix.dir }} 🖌\`${{ steps.checkov.outcome }}\`
        <details><summary>Show Scan Results</summary>

        \`\`\`\n
        ${{ process.env.CHECKOV_RESULTS }}
        \`\`\`

        </details>

        *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

        // 3. If we have a comment, update it, otherwise create a new one
        if (botComment) {
          github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: botComment.id,
            body: output
          })
        } else {
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
        }
