name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - your_TF_Dir/**
  pull_request:
    branches:
      - main
    paths:
      - your_TF_Dir/**
permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  tf_cf_deploy:     
    uses: cyberviking949/devsecops-pipelines/.github/workflows/deploy_cloudflare.yml@main
    with:
      tf_version: 1.5.7
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
