name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - your_TF_Dir/**
  pull_request:
    branches:
      - main
    paths:
      - your_TF_Dir/**
permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  tf_deploy:     
    uses: cyberviking949/devsecops-pipelines/.github/workflows/deploy_terraform.yml@main
    with:
      region: us-west-2
      tf_version: 1.5.7
    secrets:
      aws_role: ${{ secrets.AWS_ROLE }}
      ssh_key: ${{ secrets.SSH_KEY }}
